# Generated by Django 4.1.7 on 2023-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_banned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('banned', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='server_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slang_dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slang_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('sentence', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date time')),
            ],
        ),
        migrations.CreateModel(
            name='user_slang_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='date')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
