# Generated by Django 4.1.7 on 2023-05-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_slang_count_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
