# Generated by Django 4.1.7 on 2023-05-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_slang_count_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_slang_count_week',
            old_name='month',
            new_name='week',
        ),
    ]
