# Generated by Django 4.1.7 on 2023-05-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_month_user_slang_count_week_week'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_slang_count',
            new_name='user_slang_count_date',
        ),
    ]
